// Svelte Js/src/App.svelte
<script>
  import { Router, Link, Route } from "svelte-routing";
  import Home from "./routes/Home.svelte";
  import About from "./routes/About.svelte";
  import Contact from "./routes/Contact.svelte";

  export let url = "";
</script>

<Router {url}>
  <nav>
    <Link to="/">Home</Link>
    <Link to="/about">About</Link>
    <Link to="/contact">Blog</Link>
  </nav>
  <div>
    <Route path="/contact" component={Contact} />
    <Route path="/about" component={About} />
    <Route path="/"><Home /></Route>

  </div>
</Router>

// Preact/src/app.jsx
import { h } from "preact";
import { Router, Route } from "preact-router";
import { Link } from "preact-router";

//Pages Section
import Home from "./pages/Home";
import About from "./pages/About";
import Contact from "./pages/Contact";

//styles
import "./app.css";

export function App() {
  return (
    <>
      <div>
        <Router>
          <Home path="/" />
          <About path="/about" />
          <Contact path="/contact" />
        </Router>

        <nav>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/about">About</Link>
            </li>
            <li>
              <Link href="/contact">Contact</Link>
            </li>
          </ul>
        </nav>
      </div>
    </>
  );
}
